use crate::objects::traits::TypeId;
use bytes::BytesMut;

/// Origin: `server_DH_inner_data#b5890dba nonce:int128 server_nonce:int128 g:int dh_prime:string g_a:string server_time:int = Server_DH_inner_data;`
#[derive(Clone, Debug, tdlib_rs_impl::Deserialize, tdlib_rs_impl::Serialize)]
pub struct server_DH_inner_data {
    /// Value generated by client in [Step 1](https://core.telegram.org/mtproto/auth_key#dh-exchange-initiation).
    nonce: i128,
    /// Value received from server in [Step 2](https://core.telegram.org/mtproto/auth_key#dh-exchange-initiation).
    server_nonce: i128,
    g: i32,
    dh_prime: BytesMut,
    g_a: BytesMut,
    server_time: i32,
}

impl TypeId for server_DH_inner_data {
    fn type_id2() -> u32 {
        0xb5890dba
    }
}
